try {
    console.log(naoExisto);
} catch(err) {
    console.log(`dado incorreto`);
}
